# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_feedback_happy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='cutomer_name',
            new_name='customer_name',
        ),
    ]
