# Generated by Django 2.0.5 on 2018-07-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20160702_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=120)),
                ('feed_back', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('profession', models.CharField(max_length=120)),
                ('roll_no', models.CharField(max_length=120)),
                ('email_id', models.EmailField(max_length=120)),
                ('description', models.CharField(max_length=500)),
                ('picture', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('roll_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('picture', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='professor_roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Professor'),
        ),
        migrations.AddField(
            model_name='message',
            name='student_roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Student'),
        ),
    ]
