# Generated by Django 2.0.5 on 2018-07-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20180705_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_name',
            new_name='roll_no',
        ),
    ]
